modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
    modId="emoji_deco"
    version="${mod_version}"
    displayName="Emoji & Deco"
    #logoFile="examplemod.png" #optional
    credits="uqlism"
    authors="uqlism"

    description='''use emojis and richtexts in minecraft!!!'''

[[dependencies.emoji_deco]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.emoji_deco]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"